import type { PaletteDefinition } from './types'

export const PALETTES: PaletteDefinition[] = [
  /* ------------------------------------------------------------------ */
  /* CATÉGORIE 1 : NUANCES MINIMALISTES & ANTI-FATIGUE (10 PALETTES)    */
  /* ------------------------------------------------------------------ */
  {
    id: 'porcelain',
    name: 'Porcelaine Suisse',
    tagline: 'Standard Clinique Épuré',
    description: 'Minimalisme clinique suisse à haute lisibilité. Fond gris porcelaine anti-reflets et saphir médical.',
    category: 'minimalist',
    badge: 'Clinique',
    features: ['Rayon 12px', 'Anti-reflets', 'WCAG AAA'],
    colors: {
      bg: '#ebedf2',
      card: '#ffffff',
      primary: '#026aa7',
      chifa: '#047857',
      border: '#d0d7e2',
      text: '#0f172a',
    },
  },
  {
    id: 'nordic-linen',
    name: 'Lin Nordique & Encre',
    tagline: 'Éditorial Papier Chaud',
    description: 'Inspiré des revues médicales prestigieuses (The Lancet). Teinte lin reposante, zéro éblouissement.',
    category: 'minimalist',
    badge: 'Chaleur',
    features: ['Fond lin', 'Zéro éblouissement', 'Éditorial'],
    colors: {
      bg: '#f0ede6',
      card: '#faf8f5',
      primary: '#1d4ed8',
      chifa: '#047857',
      border: '#d8d1c3',
      text: '#1c1917',
    },
  },
  {
    id: 'zinc-studio',
    name: 'Zinc Satiné & Glacier',
    tagline: 'Style Linear & Raycast',
    description: 'Esthétique studio scandinave. Fond zinc velouté, contraste technique net et bleu glacier précis.',
    category: 'minimalist',
    badge: 'Ingénierie',
    features: ['Gris feutré', 'Contraste net', 'Matte'],
    colors: {
      bg: '#e8ebf0',
      card: '#ffffff',
      primary: '#0284c7',
      chifa: '#059669',
      border: '#cad2de',
      text: '#090d16',
    },
  },
  {
    id: 'sage-botanical',
    name: 'Sauge & Pin Médical',
    tagline: 'Sérénité & Phytothérapie',
    description: 'Vert sauge apaisant conçu pour réduire la fatigue oculaire et le stress cognitif lors d’usages prolongés.',
    category: 'minimalist',
    badge: 'Botanique',
    features: ['Repos oculaire', 'Vert sauge', 'Sérénité'],
    colors: {
      bg: '#edf2ee',
      card: '#f9fbf9',
      primary: '#16654f',
      chifa: '#059669',
      border: '#c9d5cb',
      text: '#14221b',
    },
  },
  {
    id: 'french-cobalt',
    name: 'Craie & Cobalt',
    tagline: 'Codex Officine Française',
    description: 'Blanc craie pur et cobalt éclatant. Lisibilité chirurgicale et contraste franc pour les professionnels.',
    category: 'minimalist',
    badge: 'Officine',
    features: ['Craie pure', 'Cobalt éclatant', 'Netteté'],
    colors: {
      bg: '#f1f3f7',
      card: '#ffffff',
      primary: '#2563eb',
      chifa: '#059669',
      border: '#cfd5e3',
      text: '#0b1329',
    },
  },
  {
    id: 'sahara-cedar',
    name: 'Dune & Cèdre de l’Atlas',
    tagline: 'Héritage Algérien Solaire',
    description: 'Harmonie des dunes sahariennes et du vert cèdre d’Afrique du Nord. Chaleureux, distinctif et noble.',
    category: 'minimalist',
    badge: 'Algérie',
    features: ['Tons sable', 'Cèdre Atlas', 'Chaleureux'],
    colors: {
      bg: '#f4f0e8',
      card: '#fbf9f5',
      primary: '#2d5a36',
      chifa: '#059669',
      border: '#d8cfbe',
      text: '#211c16',
    },
  },
  {
    id: 'braun-mineral',
    name: 'Gris Minéral & Graphite',
    tagline: 'Minimalisme Dieter Rams',
    description: 'Dépouillement monochrome allemand, neutralité absolue et ponctuation cyan minéral.',
    category: 'minimalist',
    badge: 'Monochrome',
    features: ['Neutre pur', 'Rigueur suisse', 'Chirurgical'],
    colors: {
      bg: '#eeeee9',
      card: '#ffffff',
      primary: '#0e7490',
      chifa: '#047857',
      border: '#cbcbc4',
      text: '#18181b',
    },
  },
  {
    id: 'polar-indigo',
    name: 'Brume Polaire & Indigo',
    tagline: 'Biotech & Intelligence IA',
    description: 'Nuance froide et profond indigo. Ambiance laboratoire de recherche clinique et analyse pharmacologique.',
    category: 'minimalist',
    badge: 'Biotech',
    features: ['Brume polaire', 'Indigo profond', 'High-Tech'],
    colors: {
      bg: '#eceff5',
      card: '#ffffff',
      primary: '#4338ca',
      chifa: '#0f766e',
      border: '#c8d1e0',
      text: '#0f172a',
    },
  },
  {
    id: 'mediterranean-azure',
    name: 'Perle & Azur d’Alger',
    tagline: 'Fraîcheur Méditerranéenne',
    description: 'Gris perle lumineux et bleu marin méditerranéen. Aérien, vivifiant et extrêmement soigné.',
    category: 'minimalist',
    badge: 'Maritime',
    features: ['Perle douce', 'Bleu marin', 'Aérien'],
    colors: {
      bg: '#ebf0f5',
      card: '#ffffff',
      primary: '#0369a1',
      chifa: '#047857',
      border: '#c2d2e3',
      text: '#0c1a2e',
    },
  },
  {
    id: 'ivory-emerald',
    name: 'Ivoire Impérial & Émeraude',
    tagline: 'Apothicaire de Prestige',
    description: 'Base ivoire soyeuse mariée à une émeraude impériale et des touches ambrées Chifa. Raffinement maximal.',
    category: 'minimalist',
    badge: 'Prestige',
    features: ['Ivoire soie', 'Émeraude royale', 'Raffiné'],
    colors: {
      bg: '#f2efe7',
      card: '#faf8f3',
      primary: '#065f46',
      chifa: '#047857',
      border: '#d4ccbd',
      text: '#172017',
    },
  },

  /* ------------------------------------------------------------------ */
  /* CATÉGORIE 2 : SYSTÈMES & ARCHITECTURES DE DESIGN (10 DESIGNS)      */
  /* ------------------------------------------------------------------ */
  {
    id: 'design-brutalist',
    name: 'Néo-Brutalisme Chirurgical',
    tagline: 'Angles 0px & Ombres Dures',
    description: 'Zéro arrondi, angles droits vifs de 0px, bordures franches 1.5px et ombres portées directes. Rigueur de laboratoire sans concession.',
    category: 'system',
    badge: 'Brutalisme',
    features: ['Angles 0px', 'Ombres dures', 'Bordures 1.5px'],
    colors: {
      bg: '#f4f5f8',
      card: '#ffffff',
      primary: '#1d4ed8',
      chifa: '#059669',
      border: '#94a3b8',
      text: '#0f172a',
    },
  },
  {
    id: 'design-liquid-glass',
    name: 'Verre Liquide & Aéro',
    tagline: 'Translucidité & Rayon 20px',
    description: 'Grands rayons fluides de 20px, cartes en verre givré ultra-translucide (blur 24px), reflets de lumière spéculaires et ombres douces.',
    category: 'system',
    badge: 'Aéro Glass',
    features: ['Rayon 20px', 'Verre dépoli', 'Flou 24px'],
    colors: {
      bg: '#eef3fa',
      card: '#ffffff',
      primary: '#0284c7',
      chifa: '#10b981',
      border: '#c2d5ec',
      text: '#0b1b30',
    },
  },
  {
    id: 'design-compact-dense',
    name: 'Terminal d’Officine Pro',
    tagline: 'Densité Maximale & Micro-Coins 4px',
    description: 'Conçu pour le comptoir d’officine à haut débit : micro-coins de 4px, encombrement visuel minimal pour afficher le plus de données à l’écran.',
    category: 'system',
    badge: 'Ultra-Dense',
    features: ['Micro-coins 4px', 'Élévation 0px', 'Densité Max'],
    colors: {
      bg: '#ebedf2',
      card: '#ffffff',
      primary: '#0369a1',
      chifa: '#047857',
      border: '#c8d1de',
      text: '#0f172a',
    },
  },
  {
    id: 'design-soft-pebble',
    name: 'Galet Organique & Silicone',
    tagline: 'Formes Rondes 24px & Douceur',
    description: 'Rayons très arrondis de 24px, ombres enveloppantes et toucher tactile façon dispositif médical en silicone stérile.',
    category: 'system',
    badge: 'Pebble UI',
    features: ['Rayon 24px', 'Silicone doux', 'Organique'],
    colors: {
      bg: '#f1f4f8',
      card: '#ffffff',
      primary: '#4f46e5',
      chifa: '#059669',
      border: '#d4dce7',
      text: '#131b2e',
    },
  },
  {
    id: 'design-flat-architect',
    name: 'Ligne Pure & 0 Ombre',
    tagline: 'Design Plat & Cadre 1px',
    description: 'Zéro ombre portée. La hiérarchie est entièrement sculptée par des micro-lignes chirurgicales de 1px et des alternances de plans suisses.',
    category: 'system',
    badge: 'Pure Flat',
    features: ['Zéro ombre', 'Cadre 1px pur', 'Épure suisse'],
    colors: {
      bg: '#ecf0f4',
      card: '#ffffff',
      primary: '#0f766e',
      chifa: '#047857',
      border: '#cad5e2',
      text: '#0f172a',
    },
  },
  {
    id: 'design-volumetric-card',
    name: 'Élévation Volumétrique 3D',
    tagline: 'Profondeur & Lévitation Multi-Couches',
    description: 'Ombres étagées à triple diffusion créant une physicalité forte. Les cartes de prescription et de commande semblent flotter au-dessus du plan.',
    category: 'system',
    badge: '3D Layered',
    features: ['Lévitation 3D', 'Ombres diffuses', 'Physicalité'],
    colors: {
      bg: '#e9ecf2',
      card: '#ffffff',
      primary: '#1e40af',
      chifa: '#047857',
      border: '#c5d0e0',
      text: '#0f172a',
    },
  },
  {
    id: 'design-high-contrast',
    name: 'Haute Accessibilité (WCAG AAA)',
    tagline: 'Bordures Franches & Contraste 12:1',
    description: 'Bordures épaissies de 2px très lisibles, ratios de contraste élevés (> 12:1). Idéal pour les écrans d’officine sous forte lumière du jour.',
    category: 'system',
    badge: 'WCAG AAA',
    features: ['Bordures 2px', 'Contraste 12:1', 'Lisibilité Day'],
    colors: {
      bg: '#e5e9f0',
      card: '#ffffff',
      primary: '#025a9e',
      chifa: '#036044',
      border: '#64748b',
      text: '#090d16',
    },
  },
  {
    id: 'design-telemetry-hud',
    name: 'Cockpit Télémétrique & HUD',
    tagline: 'Moniteur Hospitalier & Visière 3px',
    description: 'Rayon technique de 3px, micro-lignes cyan, sensation de visière de monitoring de soins intensifs et d’imagerie médicale.',
    category: 'system',
    badge: 'HUD Médical',
    features: ['Micro-rayon 3px', 'Cyan moniteur', 'Technique'],
    colors: {
      bg: '#e8edf3',
      card: '#ffffff',
      primary: '#0284c7',
      chifa: '#059669',
      border: '#94a3b8',
      text: '#0b1524',
    },
  },
  {
    id: 'design-paper-codex',
    name: 'Fiches Bristol d’Officine',
    tagline: 'Carton Fort & Encre Bleue',
    description: 'Cartes évoquant les fiches d’ordonnancier en carton bristol. Rayon 8px, fond lin chaud et séparation délicate façon tiroir d’apothicaire.',
    category: 'system',
    badge: 'Bristol Codex',
    features: ['Bristol chaud', 'Encre marine', 'Rayon 8px'],
    colors: {
      bg: '#eee9df',
      card: '#fcfbfa',
      primary: '#1e3a8a',
      chifa: '#2e6930',
      border: '#d5ccbe',
      text: '#1f1a14',
    },
  },
  {
    id: 'design-monochrome-braun',
    name: 'Monochrome Industriel',
    tagline: 'Rigueur Braun & Touche Sécurité',
    description: 'Neutralité absolue de l’ardoise et de l’aluminium. Un unique accent ambre de sécurité fonctionnel pour les actions.',
    category: 'system',
    badge: 'Rams Braun',
    features: ['Rayon 5px', 'Graphite minéral', 'Ambre sécurité'],
    colors: {
      bg: '#eeeeea',
      card: '#ffffff',
      primary: '#d97706',
      chifa: '#15803d',
      border: '#c8c8c2',
      text: '#18181b',
    },
  },

  /* ------------------------------------------------------------------ */
  /* CATÉGORIE 3 : IDENTITÉS CULTURELLES ALGÉRIENNES (§2.1 — 6 PALETTES)*/
  /* ------------------------------------------------------------------ */
  {
    id: 'sahara-nuit',
    name: 'Sahara Nuit',
    tagline: 'Ciel Désertique & Éclat Cramoisi',
    description: 'Ciel nocturne profond du Sahara et coucher de soleil cramoisi inspiré de Tamanrasset.',
    category: 'cultural',
    badge: 'Sahara',
    features: ['Nuit saharienne', 'Contraste rouge', 'Tamanrasset'],
    colors: {
      bg: '#1a1a2e',
      card: '#16213e',
      primary: '#e94560',
      chifa: '#34d399',
      border: '#2a3b5c',
      text: '#f1f5f9',
    },
  },
  {
    id: 'casbah-terracotta',
    name: 'Casbah Terracotta',
    tagline: 'Argile Chaude & Toits d’Alger',
    description: 'Casbah d’Alger : murs d’argile chaude, tuiles rouges et tradition pharmaceutique séculaire.',
    category: 'cultural',
    badge: 'Patrimoine',
    features: ['Terre cuite', 'Toits d’Alger', 'Argile'],
    colors: {
      bg: '#2c1810',
      card: '#3d2817',
      primary: '#e07a5f',
      chifa: '#52b788',
      border: '#543821',
      text: '#fdf0ed',
    },
  },
  {
    id: 'kabylie-emerald',
    name: 'Kabylie Émeraude',
    tagline: 'Forêts du Djurdjura & Oliviers',
    description: 'Montagnes kabyles : forêts denses, oliviers séculaires et phytothérapie ancestrale.',
    category: 'cultural',
    badge: 'Djurdjura',
    features: ['Vert émeraude', 'Phytothérapie', 'Kabylie'],
    colors: {
      bg: '#0d1b0e',
      card: '#1a2e1b',
      primary: '#52b788',
      chifa: '#2d6a4f',
      border: '#254428',
      text: '#edf7ed',
    },
  },
  {
    id: 'hoggar-violet',
    name: 'Hoggar Violet',
    tagline: 'Roches au Crépuscule & Indigo Touareg',
    description: 'Monts du Hoggar au crépuscule : formations rocheuses violettes et étoffes indigo des Touaregs.',
    category: 'cultural',
    badge: 'Grand Sud',
    features: ['Violet géologique', 'Indigo touareg', 'Hoggar'],
    colors: {
      bg: '#1a0a2e',
      card: '#240046',
      primary: '#9d4edd',
      chifa: '#38bdf8',
      border: '#3c096c',
      text: '#f8f0ff',
    },
  },
  {
    id: 'mediterranee-azure',
    name: 'Méditerranée Azur',
    tagline: 'Baie d’Alger & Fraîcheur Marine',
    description: 'Baie d’Alger : bleu profond de la Méditerranée, limpidité côtière et clarté maritime.',
    category: 'cultural',
    badge: 'Littoral',
    features: ['Bleu maritime', 'Clarté côtière', 'Baie d’Alger'],
    colors: {
      bg: '#0a1929',
      card: '#023e8a',
      primary: '#48cae4',
      chifa: '#06d6a0',
      border: '#0353a4',
      text: '#f0f9ff',
    },
  },
  {
    id: 'constantine-or',
    name: 'Constantine Or',
    tagline: 'Ponts Suspendus & Pierre Dorée',
    description: 'Cité des ponts : pierres dorées surplombant les gorges du Rhummel, héritage antique.',
    category: 'cultural',
    badge: 'Rhummel',
    features: ['Pierre dorée', 'Ponts antiques', 'Gorges'],
    colors: {
      bg: '#1c1410',
      card: '#3e2723',
      primary: '#d4a373',
      chifa: '#4e937a',
      border: '#5d3a37',
      text: '#fff8f0',
    },
  },

  /* ------------------------------------------------------------------ */
  /* CATÉGORIE 4 : PALETTES SAISONNIÈRES (§2.2 — 6 PALETTES)            */
  /* ------------------------------------------------------------------ */
  {
    id: 'ramadan-nuit',
    name: 'Ramadan Nuit',
    tagline: 'Croissant Lunaire & Chaleur de l’Iftar',
    description: 'Nuits sacrées de Ramadan : ciel indigo profond, croissant argenté et chaleur de l’iftar.',
    category: 'seasonal',
    badge: 'Ramadan',
    features: ['Indigo profond', 'Croissant d’or', 'Iftar'],
    colors: {
      bg: '#0f0c29',
      card: '#1a1a2e',
      primary: '#e94560',
      chifa: '#fbbf24',
      border: '#2d2b55',
      text: '#f8fafc',
    },
  },
  {
    id: 'eid-or',
    name: 'Aïd Or',
    tagline: 'Célébration Dorée & Allégresse',
    description: 'Célébrations de l’Aïd al-Fitr et Aïd al-Adha : éclats d’or, festivités et bienveillance.',
    category: 'seasonal',
    badge: 'Fêtes',
    features: ['Or radieux', 'Festivité', 'Tradition'],
    colors: {
      bg: '#1a1208',
      card: '#2d1f0f',
      primary: '#ffd700',
      chifa: '#34d399',
      border: '#4d3419',
      text: '#fffdf5',
    },
  },
  {
    id: 'printemps-tlemcen',
    name: 'Printemps Tlemcen',
    tagline: 'Fleur d’Oranger & Collines Vertes',
    description: 'Printemps de Tlemcen : collines fleuries, senteurs de fleur d’oranger et douceur.',
    category: 'seasonal',
    badge: 'Floraison',
    features: ['Fleur d’oranger', 'Vert doux', 'Tlemcen'],
    colors: {
      bg: '#0d1f0d',
      card: '#1a2e1a',
      primary: '#83c5be',
      chifa: '#06d6a0',
      border: '#264626',
      text: '#f0fdf4',
    },
  },
  {
    id: 'ete-bejaia',
    name: 'Été Béjaïa',
    tagline: 'Cap Carbon & Soleil Méditerranéen',
    description: 'Été sur la côte des Babors : soleil doré, falaises du Cap Carbon et mer turquoise.',
    category: 'seasonal',
    badge: 'Cap Carbon',
    features: ['Soleil d’été', 'Mer turquoise', 'Béjaïa'],
    colors: {
      bg: '#003049',
      card: '#005f73',
      primary: '#ffbe0b',
      chifa: '#0a9396',
      border: '#0a758f',
      text: '#fdfbf7',
    },
  },
  {
    id: 'automne-setif',
    name: 'Automne Sétif',
    tagline: 'Hauts Plateaux & Moissons d’Ambre',
    description: 'Hauts plateaux sétifiens en automne : champs de blé dorés, lumière rasante et terre fertile.',
    category: 'seasonal',
    badge: 'Hauts Plateaux',
    features: ['Ambre moisson', 'Terres hautes', 'Sétif'],
    colors: {
      bg: '#1a1612',
      card: '#283618',
      primary: '#bc6c25',
      chifa: '#606c38',
      border: '#3e4a2a',
      text: '#fefae0',
    },
  },
  {
    id: 'hiver-ghardaia',
    name: 'Hiver Ghardaïa',
    tagline: 'Vallée du M’zab & Lumière Oasienne',
    description: 'Hiver dans la vallée du M’zab : architecture millénaire, feux d’oasis et fraîcheur nocturne.',
    category: 'seasonal',
    badge: 'M’zab',
    features: ['Architecture M’zab', 'Tons sable', 'Ghardaïa'],
    colors: {
      bg: '#1d1d1d',
      card: '#3a3a3a',
      primary: '#dda15e',
      chifa: '#588157',
      border: '#4f4f4f',
      text: '#f8f9fa',
    },
  },

  /* ------------------------------------------------------------------ */
  /* CATÉGORIE 5 : PALETTES CLINIQUES FONCTIONNELLES (§2.3 — 6 PALETTES)*/
  /* ------------------------------------------------------------------ */
  {
    id: 'chirurgie-pure',
    name: 'Chirurgie Pure',
    tagline: 'Bloc Opératoire & Anti-Reflet',
    description: 'Environnement stérile : noir absolu anti-éblouissement et vert néon chirurgical à haute visibilité.',
    category: 'clinical',
    badge: 'Bloc Opératoire',
    features: ['Anti-éblouissement', 'Vert fluo', 'Contraste pur'],
    colors: {
      bg: '#0a0a0a',
      card: '#141414',
      primary: '#00ff88',
      chifa: '#00e5ff',
      border: '#262626',
      text: '#ffffff',
    },
  },
  {
    id: 'urgence-rouge',
    name: 'Urgence Rouge',
    tagline: 'Signal Critique & Vigilance Immédiate',
    description: 'Mode garde et réanimation : fond sombre profond et rouge écarlate stimulant la vigilance.',
    category: 'clinical',
    badge: 'SAMU / Urgences',
    features: ['Alerte rouge', 'Garde de nuit', 'Vigilance'],
    colors: {
      bg: '#1a0000',
      card: '#2d0000',
      primary: '#ff3333',
      chifa: '#fbbf24',
      border: '#4a0000',
      text: '#fff5f5',
    },
  },
  {
    id: 'nuit-pharmacie',
    name: 'Nuit Pharmacie',
    tagline: 'Garde Nocturne & Respect Circadien',
    description: 'Conçu pour le comptoir de nuit : bleu nuit profond sans lumière bleue agressive.',
    category: 'clinical',
    badge: 'Garde 24/7',
    features: ['Repos oculaire', 'Zéro fatigue', 'Nocturne'],
    colors: {
      bg: '#0a0e1a',
      card: '#111827',
      primary: '#4cc9f0',
      chifa: '#10b981',
      border: '#1f293d',
      text: '#f1f5f9',
    },
  },
  {
    id: 'pediatrie-joy',
    name: 'Pédiatrie Douceur',
    tagline: 'Mode Enfant & Posologie Pédiatrique',
    description: 'Ambiance pédiatrique rassurante : indigo velouté et jaune solaire apaisant.',
    category: 'clinical',
    badge: 'Pédiatrie',
    features: ['Indigo chaleureux', 'Jaune solaire', 'Enfant'],
    colors: {
      bg: '#1e1b4b',
      card: '#312e81',
      primary: '#fbbf24',
      chifa: '#34d399',
      border: '#4338ca',
      text: '#fef3c7',
    },
  },
  {
    id: 'geriatrie-contrast',
    name: 'Gériatrie Haute Visibilité',
    tagline: 'Contraste Maximal & Basse Vision',
    description: 'Pour les praticiens âgés et patients malvoyants : contraste noir/blanc extrême sans fioritures.',
    category: 'clinical',
    badge: 'Accessibilité',
    features: ['Noir/Blanc absolu', 'Grands caractères', 'WCAG AAA+'],
    colors: {
      bg: '#000000',
      card: '#1a1a1a',
      primary: '#ffffff',
      chifa: '#22c55e',
      border: '#404040',
      text: '#ffffff',
    },
  },
  {
    id: 'telemedecine-calm',
    name: 'Téléconsultation Sérénité',
    tagline: 'Consultation Vidéo & Écoute',
    description: 'Bleu ardoise et émeraude médicale apaisant le stress des patients lors d’échanges à distance.',
    category: 'clinical',
    badge: 'Téléconsultation',
    features: ['Bleu apaisant', 'Émeraude doux', 'Sérénité'],
    colors: {
      bg: '#0f172a',
      card: '#1e293b',
      primary: '#10b981',
      chifa: '#38bdf8',
      border: '#334155',
      text: '#f8fafc',
    },
  },

  /* ------------------------------------------------------------------ */
  /* CATÉGORIE 6 : PALETTES EXPÉRIMENTALES (§2.4 — 6 PALETTES)          */
  /* ------------------------------------------------------------------ */
  {
    id: 'cyber-sahara',
    name: 'Cyber Sahara',
    tagline: 'Esthétique Cyberpunk & Néo-Officine',
    description: 'Noir onyx et vert néon acide pour les préparateurs et pharmaciens avant-gardistes.',
    category: 'experimental',
    badge: 'Futuriste',
    features: ['Vert acide', 'Noir onyx', 'Cyberpunk'],
    colors: {
      bg: '#0a0a0a',
      card: '#0d0d0d',
      primary: '#00ffaa',
      chifa: '#f59e0b',
      border: '#222222',
      text: '#f0fdf4',
    },
  },
  {
    id: 'vaporwave-alger',
    name: 'Vaporwave Alger',
    tagline: 'Nostalgie Rétro-Futuriste & Synthwave',
    description: 'Pourpre nocturne et rose néon vibrant évoquant le crépuscule méditerranéen des années 80.',
    category: 'experimental',
    badge: 'Synthwave',
    features: ['Pourpre néon', 'Rose magenta', 'Rétro'],
    colors: {
      bg: '#1a0b2e',
      card: '#2d1b4e',
      primary: '#ff6ec7',
      chifa: '#7000ff',
      border: '#442875',
      text: '#fdf4ff',
    },
  },
  {
    id: 'mono-noir',
    name: 'Mono Noir Typographique',
    tagline: 'Typographie Pure & Zéro Distraction',
    description: 'Aucune couleur superflue : noir carbone et blanc papier pour une concentration clinique totale.',
    category: 'experimental',
    badge: 'Minimalisme Pur',
    features: ['Monochrome', 'Typographie', 'Clarté'],
    colors: {
      bg: '#000000',
      card: '#0a0a0a',
      primary: '#f8f8f8',
      chifa: '#a3a3a3',
      border: '#262626',
      text: '#ffffff',
    },
  },
  {
    id: 'saffron-dawn',
    name: 'Aurore Safran',
    tagline: 'Épices de Ghardaïa & Ambre Chaud',
    description: 'Safran pur, cannelle et ambre précieux inspirés des herboristeries traditionnelles du M’zab.',
    category: 'experimental',
    badge: 'Épices',
    features: ['Safran d’or', 'Ambre chaud', 'Herboristerie'],
    colors: {
      bg: '#0d0a00',
      card: '#1a1400',
      primary: '#ffb700',
      chifa: '#10b981',
      border: '#332900',
      text: '#fffdf0',
    },
  },
  {
    id: 'glacier-mint',
    name: 'Menthe Glacée & Perfusion',
    tagline: 'Clarté Cristalline & Solutions IV',
    description: 'Bleu glacier et menthe givrée inspirés de la compatibilité des perfusions et solutés injectables.',
    category: 'experimental',
    badge: 'Injectables',
    features: ['Menthe cristalline', 'Glacier IV', 'Stérilité'],
    colors: {
      bg: '#001220',
      card: '#002030',
      primary: '#7fffd4',
      chifa: '#38bdf8',
      border: '#003852',
      text: '#f0fdfa',
    },
  },
  {
    id: 'terracotta-sky',
    name: 'Ciel Terracotta',
    tagline: 'Terre Rouge & Couchant Saharien',
    description: 'Terre cuite méditerranéenne et orange flamboyant du ciel maghrébin au crépuscule.',
    category: 'experimental',
    badge: 'Maghreb',
    features: ['Orange flamboyant', 'Terre cuite', 'Crépuscule'],
    colors: {
      bg: '#1a0f0a',
      card: '#2d1a0f',
      primary: '#ff7849',
      chifa: '#22c55e',
      border: '#472b1a',
      text: '#fff7ed',
    },
  },
]
